server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TaskManagerApp
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  client:
    url: http://localhost:4200

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    org.springframework: INFO
    com.edu: DEBUG